### ISSUE TITLE
Recherche documentaire à faire

### ISSUE THREAD

**Issue by moussadiallo** [aichou96/projetperso#1]
Projet très interessant, seulement il và falloir se renseigner dans le domaine légal de l'application, il me semble qu'au Sénégal l'adoption n'est pas permise (à creuser), par contre il faut insister sur le côté parainage.  Documentation à fournir (photos, histoire marquant ......)

**Comment by aichou96** [comment]
documentation faite

**Comment by moussadiallo** [comment]
Très bien
