### ISSUE TITLE
Comment rajouter une image ?

### ISSUE THREAD

**Issue by moussadiallo** [aichou96/projetperso#2]
Pour rajouter une image dans le wiki il faut le référencer par rapport à un lien sur le net, en gros il fut que l'image soit disponible sur un serveur public. Vous pouvez utiliser le site github lui même:
- j'ai clôner le projet
- créer un dossier images y ai mis une image (local)
- commit et push (vers le remote)
Ainsi je dispose sur github.com l'image en question, je n'ai plus qu'à le référencer dans mon wiki

**Comment by aichou96** [comment]
message compris
